import jsPDF from "jspdf";
import type { DataRow } from "./data";

export interface ExportReportArgs {
  data: DataRow[];
  aiInsight: string;
  fileName: string;
}

export function exportReport({ data, aiInsight, fileName }: ExportReportArgs): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // ── Constants ────────────────────────────────────────────────────────────
  const PW = 210;
  const PH = 297;
  const M = 15;
  const CW = PW - M * 2; // 180mm content width

  // Colours
  type RGB = [number, number, number];
  const BG:      RGB = [15,  15,  15];
  const SURFACE: RGB = [25,  30,  40];
  const TEXT:    RGB = [229, 229, 229];
  const GOLD:    RGB = [201, 168, 76];
  const MUTED:   RGB = [130, 130, 130];
  const DIM:     RGB = [60,  60,  60];
  const BORDER:  RGB = [40,  48,  60];
  const HDR_ROW: RGB = [30,  38,  52];
  const ALT_ROW: RGB = [20,  25,  35];

  const fill = (c: RGB) => doc.setFillColor(c[0], c[1], c[2]);
  const tc   = (c: RGB) => doc.setTextColor(c[0], c[1], c[2]);
  const dc   = (c: RGB) => doc.setDrawColor(c[0], c[1], c[2]);

  const FOOTER_Y = PH - 8;

  let y = 0;

  // ── Page helpers ─────────────────────────────────────────────────────────
  const fillPage = () => {
    fill(BG);
    doc.rect(0, 0, PW, PH, "F");
  };

  const newPage = () => {
    doc.addPage();
    fillPage();
    y = M;
  };

  /** Ensure `needed` mm fits before the footer; add a new page if not. */
  const ensure = (needed: number) => {
    if (y + needed > FOOTER_Y - 4) newPage();
  };

  /** Clip a string to fit within maxMm at the current font/size. */
  const clip = (str: string, maxMm: number): string => {
    if (!str) return "";
    const sz = doc.getFontSize();
    const sc = (doc.internal as { scaleFactor: number }).scaleFactor;
    const w  = (s: string) => (doc.getStringUnitWidth(s) * sz) / sc;
    if (w(str) <= maxMm) return str;
    let s = str;
    while (s.length > 1 && w(s + "…") > maxMm) s = s.slice(0, -1);
    return s + "…";
  };

  const hRule = (yPos: number, color: RGB, weight = 0.3) => {
    dc(color);
    doc.setLineWidth(weight);
    doc.line(M, yPos, PW - M, yPos);
  };

  // ── Footers (drawn after all pages are built) ─────────────────────────
  const drawFooter = (pageNum: number, total: number) => {
    doc.setPage(pageNum);
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    tc(DIM);
    doc.text(
      "Generated by StreamIQ · Lotus AI · getlotusai.com",
      PW / 2,
      FOOTER_Y,
      { align: "center" }
    );
    doc.text(`${pageNum} / ${total}`, PW - M, FOOTER_Y, { align: "right" });
  };

  // ── Page 1 ───────────────────────────────────────────────────────────────
  fillPage();

  // ── HEADER ───────────────────────────────────────────────────────────────
  y = 25;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  tc(GOLD);
  doc.text("StreamIQ", M, y);

  y += 9;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  tc(MUTED);
  doc.text("by Lotus AI", M, y);

  y += 7;
  hRule(y, GOLD, 0.4);
  y += 8;

  // ── REPORT METADATA ───────────────────────────────────────────────────────
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "bold");
  tc(DIM);
  doc.text("REPORT METADATA", M, y);
  y += 5;

  const now = new Date();
  const dateLabel = now.toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  const timeLabel = now.toLocaleTimeString("en-US", {
    hour: "2-digit", minute: "2-digit",
  });

  const metaRows: [string, string][] = [
    ["File",      fileName],
    ["Records",   `${data.length}`],
    ["Generated", `${dateLabel} at ${timeLabel}`],
  ];

  for (const [label, value] of metaRows) {
    ensure(6);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    tc(MUTED);
    doc.text(`${label}:`, M, y);
    doc.setFont("helvetica", "normal");
    tc(TEXT);
    doc.text(value, M + 22, y);
    y += 5.5;
  }
  y += 5;

  // ── KPI SUMMARY ───────────────────────────────────────────────────────────
  ensure(56);
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "bold");
  tc(DIM);
  doc.text("KPI SUMMARY", M, y);
  y += 5;

  const safeN = data.length || 1;
  const kpis = [
    {
      label: "Total Streams",
      value: `${data.reduce((s, d) => s + (Number(d.Streams_M) || 0), 0).toFixed(0)}M`,
    },
    {
      label: "Total Revenue",
      value: `$${data.reduce((s, d) => s + (Number(d.Revenue_M) || 0), 0).toFixed(0)}M`,
    },
    {
      label: "Avg Rating",
      value: (data.reduce((s, d) => s + (Number(d.Rating) || 0), 0) / safeN).toFixed(1),
    },
    {
      label: "Avg Completion",
      value: `${(
        (data.reduce((s, d) => s + (Number(d.Completion_Rate) || 0), 0) / safeN) * 100
      ).toFixed(1)}%`,
    },
  ];

  const KW = (CW - 6) / 2; // card width
  const KH = 22;            // card height
  const KG = 5;             // gap between rows

  kpis.forEach((kpi, i) => {
    const col = M + (i % 2) * (KW + 6);
    const row = y + Math.floor(i / 2) * (KH + KG);

    fill(SURFACE);
    doc.roundedRect(col, row, KW, KH, 2, 2, "F");
    dc(BORDER);
    doc.setLineWidth(0.2);
    doc.roundedRect(col, row, KW, KH, 2, 2, "S");

    doc.setFontSize(6.5);
    doc.setFont("helvetica", "normal");
    tc(MUTED);
    doc.text(kpi.label.toUpperCase(), col + 4, row + 7);

    doc.setFontSize(17);
    doc.setFont("helvetica", "bold");
    tc(GOLD);
    doc.text(kpi.value, col + 4, row + 17);
  });

  y += 2 * (KH + KG) + 5;

  // ── AI INSIGHTS ───────────────────────────────────────────────────────────
  ensure(20);
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "bold");
  tc(DIM);
  doc.text("AI INSIGHTS", M, y);
  y += 6;

  // Set insight font before splitTextToSize so wrapping uses correct metrics
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const insightLines = doc.splitTextToSize(aiInsight, CW - 8);
  const lineH = 5.5;
  const insightBoxH = insightLines.length * lineH + 8;

  if (y + insightBoxH <= FOOTER_Y - 4) {
    // Fits on one page — draw a contained background box
    fill(SURFACE);
    doc.roundedRect(M, y, CW, insightBoxH, 2, 2, "F");
    dc([80, 65, 30]); // muted gold border
    doc.setLineWidth(0.3);
    doc.roundedRect(M, y, CW, insightBoxH, 2, 2, "S");
    y += 5;
    tc(TEXT);
    for (const line of insightLines) {
      doc.text(line as string, M + 4, y);
      y += lineH;
    }
    y += 5;
  } else {
    // Very long insight — render with page breaks, no full box
    tc(TEXT);
    for (const line of insightLines) {
      ensure(lineH + 2);
      doc.text(line as string, M + 4, y);
      y += lineH;
    }
    y += 5;
  }

  // ── DATA TABLE ────────────────────────────────────────────────────────────
  ensure(20);
  doc.setFontSize(6.5);
  doc.setFont("helvetica", "bold");
  tc(DIM);
  doc.text("DATA TABLE", M, y);
  y += 6;

  const tableRows = data.slice(0, 20);
  if (tableRows.length > 0) {
    const headers = Object.keys(tableRows[0]);
    const colW  = CW / headers.length;
    const ROW_H = 6.5;
    const HDR_H = 7;

    // Header row
    ensure(HDR_H + ROW_H * 2);
    fill(HDR_ROW);
    doc.rect(M, y, CW, HDR_H, "F");
    doc.setFontSize(5.5);
    doc.setFont("helvetica", "bold");
    tc(MUTED);
    headers.forEach((h, i) => {
      const label = h.replace(/_/g, " ").toUpperCase();
      doc.text(clip(label, colW - 3), M + i * colW + 2, y + 4.5);
    });

    y += HDR_H;
    hRule(y, BORDER, 0.3);

    // Data rows
    tableRows.forEach((row, ri) => {
      ensure(ROW_H + 1);
      if (ri % 2 === 1) {
        fill(ALT_ROW);
        doc.rect(M, y, CW, ROW_H, "F");
      }
      doc.setFontSize(6.5);
      doc.setFont("helvetica", "normal");
      Object.values(row).forEach((val, ci) => {
        const isNum = typeof val === "number";
        tc(isNum ? TEXT : MUTED);
        const str = isNum ? val.toLocaleString() : String(val);
        doc.text(clip(str, colW - 3), M + ci * colW + 2, y + 4.5);
      });
      dc(BORDER);
      doc.setLineWidth(0.1);
      doc.line(M, y + ROW_H, M + CW, y + ROW_H);
      y += ROW_H;
    });
  }

  // ── FOOTERS ───────────────────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    drawFooter(p, totalPages);
  }

  // ── SAVE ──────────────────────────────────────────────────────────────────
  const isoDate = now.toISOString().split("T")[0];
  doc.save(`streamiq-report-${isoDate}.pdf`);
}
